// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import (
	"appsrv/pkg/auth"
	"appsrv/pkg/bog"
	"appsrv/pkg/config"
	"appsrv/pkg/db"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func createServeAppCommand() *cobra.Command {
	pgDB := db.ProvideSingleton()
	serverConfig := config.ProvideSingleton()
	wrapper := auth.RoleGuard(pgDB, serverConfig)
	v := resolveControllerSet()
	mux := createServerMux(wrapper, v)
	logger := bog.ProvideSingleton()
	runner := createServerRunner(mux, pgDB, logger, serverConfig)
	command := createApplicationRunner(runner)
	return command
}
